### ISSUE TITLE
Why not generate Bulletproof font rule? 

### ISSUE THREAD

**Issue by Genuifx** [seaneking/postcss-fontpath#11]
As Paul said in [Bulletproof](https://www.paulirish.com/2009/bulletproof-font-face-implementation-syntax/)

It looks Bulletproof Method is useful for cross browsers.

**Comment by madeleineostoja** [comment]
It can optionally, if you want to support IE8, see https://github.com/seaneking/postcss-fontpath#ie8-support

**Comment by Genuifx** [comment]
another question is why not generate rule like this:
```css
@font-face {
  font-family: 'My Font';
  src: url("/path/to/font/file.woff2") format('woff2'),
       url("/path/to/font/file.woff") format('woff'),
       url("/path/to/font/file.ttf") format('truetype'),
       url("/path/to/font/file.svg") format('svg');
  font-weight: normal;
  font-style: normal;
}
```

On one hand, `woff` font size is smaller than 'eot', also `woff` is w3c recommendation. On another hand, `.eot` only supported by IE, but in IE9+.  we can use `.woff`(according to [caniuse](https://caniuse.com/#search=woff))

if we just support android4.4+, we can be more concise:
```css
@font-face {
  font-family: 'My Font';
  src: url("/path/to/font/file.woff2") format('woff2'),
       url("/path/to/font/file.woff") format('woff');
  font-weight: normal;
  font-style: normal;
}
```
